<?php
$a_config[0] = array(
					 "name"					=> $this->_get_lexique('Associations',1),
					 "addon"				=> "default",
					 "table"				=> "associations",
					 "code"					=> "associations",
					 "tri"					=> "association_label DESC",
					 "cle"					=> "association_id",
					 "condition"			=> "t0.archive=0",
					 "condition_include"	=> true,					 
					 "optim_search" 		=> array(
												"online" 		=> array(
													"champ"						=> "online",
													"title"						=> $this->_get_lexique('Etat',1),
													"type"						=> "radio",
													"data"						=> array("0"=>$this->_get_lexique('online',1),"1"=>$this->_get_lexique('Valider',1),"2"=>$this->_get_lexique('offline',1))
												),
					 ),
    				 "actions"				=> array('edit', 'delete'),
    				 "more_actions"			=> array('add', 'search'),
					 "champs"				=> array( 	
					 							"online" => array(
														"champ"					=> "online",
														"title"					=> $this->_get_lexique('online',1),
														"type"					=> "checkbox",
														"icon"					=> "switch",
														"on_list"				=> true,
														"zone"					=> "action",
														"priority"				=> 1,
												),
												"association_label" => array(
													"champ"						=> "association_label",
													"title"						=> $this->_get_lexique("Nom de l'assocxiation",1),
													"type"						=> "varchar",
													"maxlength"					=> 255,
													"verif"						=> array("mandatory"),
													"error_label"				=> $this->_get_lexique('Saisie du nom incorrecte',1),
													"on_list"					=> true,
													"list_css"					=> "width:7%;"
												),
												"association_address" => array(
													"champ"						=> "association_address",
													"title"						=> $this->_get_lexique("Adresse de l'assocxiation",1),
													"type"						=> "varchar",
													"maxlength"					=> 255,
													"verif"						=> array("mandatory"),
													"error_label"				=> $this->_get_lexique("Saisie de l'adresse incorrecte",1),
												),
												"association_zip" => array(
													"champ"						=> "association_zip",
													"title"						=> $this->_get_lexique("Code postal de l'association",1),
													"type"						=> "varchar",
													"maxlength"					=> 255,
													"verif"						=> array("mandatory"),
													"error_label"				=> $this->_get_lexique('Saisie du Code postal incorrecte',1),
												),
												"association_city" => array(
													"champ"						=> "association_city",
													"title"						=> $this->_get_lexique("Ville de l'assocxiation",1),
													"type"						=> "varchar",
													"maxlength"					=> 255,
													"verif"						=> array("mandatory"),
													"error_label"				=> $this->_get_lexique("Saisie de la ville incorrecte",1),
												),
												"association_address2" => array(
													"champ"						=> "association_address2",
													"title"						=> $this->_get_lexique("Adresse 2 de l'assocxiation",1),
													"type"						=> "varchar",
													"maxlength"					=> 255,
													"verif"						=> array("mandatory"),
													"error_label"				=> $this->_get_lexique("Saisie de l'adresse 2 incorrecte",1),
												),
												"association_zip2" => array(
													"champ"						=> "association_zip2",
													"title"						=> $this->_get_lexique("Code postal 2 de l'association",1),
													"type"						=> "varchar",
													"maxlength"					=> 255,
													"verif"						=> array("mandatory"),
													"error_label"				=> $this->_get_lexique('Saisie du Code postal 2 incorrecte',1),
												),
												"association_city2" => array(
													"champ"						=> "association_city2",
													"title"						=> $this->_get_lexique("Ville 2 de l'association",1),
													"type"						=> "varchar",
													"maxlength"					=> 255,
													"verif"						=> array("mandatory"),
													"error_label"				=> $this->_get_lexique('Saisie de la ville 2 incorrecte',1),
												),
												"association_phone" => array(
													"champ"						=> "association_phone",
													"title"						=> $this->_get_lexique("Téléphone de l'associqation",1),
													"type"						=> "varchar",
													"maxlength"					=> 255,
												),
												"association_email" => array(
													"champ"						=> "association_email",
													"title"						=> $this->_get_lexique("E-mailde l'association",1),
													"type"						=> "varchar",
													"maxlength"					=> 255,
													"verif"						=> array("mandatory"), 
													"error_label"				=> $this->_get_lexique("Saisie de l'email incorrecte",1),
												),
												"siret" => array(
													"champ"						=> "siret",
													"title"						=> $this->_get_lexique("SIRET / SIREN",1),
													"type"						=> "varchar",
													"maxlength"					=> 255,
													"error_label"				=> $this->_get_lexique("Saisie du SIRET incorrecte",1),
												),
												"rna" => array(
													"champ"						=> "rna",
													"title"						=> $this->_get_lexique("RNA",1),
													"type"						=> "varchar",
													"maxlength"					=> 255,
													"error_label"				=> $this->_get_lexique("Saisie du RNA incorrecte",1),
												),
												"fname" => array(
													"champ"						=> "fname",
													"title"						=> $this->_get_lexique("Prénom",1),
													"type"						=> "varchar",
													"maxlength"					=> 255,
													"error_label"				=> $this->_get_lexique("Saisie du prénom incorrecte",1),
												),
												"lname" => array(
													"champ"						=> "lname",
													"title"						=> $this->_get_lexique("Nom l'association",1),
													"type"						=> "varchar",
													"maxlength"					=> 255,
													"error_label"				=> $this->_get_lexique("Saisie du nom incorrecte",1),
												),
												"function" => array(
													"champ"						=> "function",
													"title"						=> $this->_get_lexique("Fonction",1),
													"type"						=> "varchar",
													"maxlength"					=> 255,
													"error_label"				=> $this->_get_lexique("Saisie de la fonction incorrecte",1),
												),
												
											),			
					"auto_fields"	=> array(),
);
?>