[development]
;******************************
;******************************
;GENERAL VARS
;******************************
;******************************
	;default webserver Apache / Nginx
	configuration.webserver 							= "apache"


	;default API
	configuration.isApi 								= false
	configuration.apikey 								= ''
	configuration.debug									= false
	configuration.ApiUri 								= ''
	
	configuration.isSendinblue							= true
	configuration.sendinblue.apikey						= ''

	configuration.apiWordpressUri						= ''

	;is this application using categorizer class to detect the device ?
	configuration.device 								= 1
	
	;default device
	configuration.default.device 						= 'desktop'
	
	;is it an secure extranet 
	configuration.default.extranet 						= true

	;active cache system
	configuration.default.cache 						= false

	;time cache system
	configuration.default.cacheTime 					= '86400'
	
	;initialisation of default language if not using multilingue website
	configuration.default.i_lang 						= 1
	configuration.default.s_lang 						= 'fr'
	configuration.default.s_translation 				= 'fr_FR'

	configuration.default.notification 					= true
	
	;is multilingue
	configuration.multilang 							= true
	
	;initialisation of the rel_mode. Using minifier of js and css files
	configuration.minifier						 		= false
	
	;initialisation of the rel_id. This variable is necessary if using the minifier of js and css files
	configuration.rel						 			= 'default'
		
	;default_view is used to switch between general, frontoffice and backoffice 
	configuration.default.view							= 'general'
		
	;name of the website
	configuration.default.name							= 'brand-universe'
	
	;max filesize upload allowed	
	configuration.default.upload_max_filesize 			= 1024000;
	
	;different path for upload
	configuration.default.uploadFolder 					= '/../web/content/bdd/'
	configuration.default.uploadSecureFolder 			= '/../secure/'
	configuration.default.uploadTemp 					= '/../_tmp/'
	configuration.default.tiny							= 'files'
	
	;pattern
	configuration.default.preg_pattern.date				= '/^(0[1-9]|[1-2][0-9]|3[0-1])-(0[1-9]|1[0-2])-[0-9]{4}$/'
	configuration.default.preg_pattern.email			= '#^[a-zA-Z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$#'
	configuration.default.preg_pattern.tel				= '#^0[0-9]([ .-]?[0-9]{2}){4}$#'
	configuration.default.preg_pattern.num				= '#^[0-9]#'
	configuration.default.pattern.dates					= 'dd-mm-YYYY'
	
	;dates
	configuration.default.month[0] 						= 'janvier';
	configuration.default.month[1] 						= 'février';
	configuration.default.month[2] 						= 'mars';
	configuration.default.month[3] 						= 'avril';
	configuration.default.month[4] 						= 'mai';
	configuration.default.month[5] 						= 'juin';
	configuration.default.month[6] 						= 'juillet';
	configuration.default.month[7] 						= 'août';
	configuration.default.month[8] 						= 'septembre';
	configuration.default.month[9] 						= 'octobre';
	configuration.default.month[10] 					= 'novembre';
	configuration.default.month[11] 					= 'décembre';
	
;******************************
;******************************
;FRONTOFFICE VARS
;******************************
;******************************
	;boolean to set if the print option is available. Can be set in each controller
	configuration.print									= true
	
	;boolean to set if the sharing option is available. Can be set in each controller
	configuration.mail									= true
		
	;this web site is using a cart
	configuration.cart							 		= false


;******************************
;******************************
;BACKOFFICE VARS
;******************************
;******************************
	;initialisation of the shutdown option. 
	configuration.shutdown 								= false
		
	;kind of multilingue website
	;	- 1 for standard : each langage is a particular website 
	;	- 2 : 
	;	- 3 : 
	configuration.kindmultilingue						= 1
	
	;template name
	configuration.template								= 'default'

	;boolean if web site needs authtntification
	configuration.needauth 								= false

	;boolean if web site needs authtntification
	configuration.sso 								= false
	
	;backoffice tree is sortable or not (jquery plugin)
	configuration.sortable 								= true
	
	;backoffice delete or archiv
	configuration.archiv 								= true
	
	;backoffice activate log
	configuration.log 									= false