[development]
	;set the SMTP server port
	mailer.secure								= "tls"

		;enable SMTP authentication
	mailer.smtp_auth							= true
	
	;set the SMTP server port
	mailer.port									= 587
	
	;SMTP server
	mailer.host									= 'smtp-relay.brevo.com'
	 
	;SMTP server username
	mailer.username								= ''

	;SMTP server sender
	mailer.sender								= ''
	
	;SMTP server password
	mailer.password								= ''
	
	;SMTP server name
	mailer.name									= 'ROSALIE'
	
	;SMTP server email
    mailer.contact[]							= ''